unstable_features = true
binop_separator = "Back"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "PreferSameLine"
combine_control_expr = false
comment_width = 80
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
empty_item_single_line = true
force_multiline_blocks = false
format_macro_matchers = true
format_macro_bodies = true
format_strings = false
tab_spaces = 4
imports_indent = "Visual"
imports_layout = "Mixed"

#still not totally sold on this option, but at least the spacing is consistent
indent_style = "Block"
#indent_style = "Visual"

match_arm_blocks = true
match_block_trailing_comma = true
trailing_comma = "Vertical"
merge_derives = true
merge_imports = false
newline_style = "Unix"
overflow_delimited_expr = false
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_lit_single_line = true
trailing_semicolon = false
type_punctuation_density = "Wide"
use_field_init_shorthand = true
where_single_line = true
wrap_comments = true
max_width = 100

fn_args_layout = "Compressed"
#fn_single_line = false
#preserve_block_start_blank_lines = false
#removed_nested_parens = true
#space_before_fn_sig_paren = false
#space_around_attr_eq = true

# build.rs has some long strings that get formatted regardless of what `format_strings` equals
ignore = [ "build.rs" ]
